<?xml version="1.0" encoding="utf-8"?><Database Name="Finals" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=EVANLAPTOP\SQLEXPRESS;Initial Catalog=Finals;Integrated Security=True;Connect Timeout=30;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="_2Y_2324_FinalsProject.Properties.Settings" SettingsPropertyName="FinalsConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BloodType" Member="BloodTypes">
    <Type Name="BloodType">
      <Column Name="BloodType_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BloodType_Desc" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="BloodType_Patient" Member="Patients" ThisKey="BloodType_Id" OtherKey="BloodType_Id" Type="Patient" />
    </Type>
  </Table>
  <Table Name="dbo.HealthInfo" Member="HealthInfos">
    <Type Name="HealthInfo">
      <Column Name="HealthInfo_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Patient_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HealthInfo_Medications" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HealthInfo_Allergies" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HealthInfo_Surgeries" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="HealthInfo_FamilyHistory" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="Patient_HealthInfo" Member="Patient" ThisKey="Patient_Id" OtherKey="Patient_Id" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="Patient_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Patient_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Patient_Sex" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Patient_Height" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Patient_Weight" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Patient_Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Patient_Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="BloodType_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Patient_EmergencyContactName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Patient_EmergencyContactNum" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PatientStatus_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Patient_Image" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Staff_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Patient_HealthInfo" Member="HealthInfos" ThisKey="Patient_Id" OtherKey="Patient_Id" Type="HealthInfo" />
      <Association Name="Patient_Vital" Member="Vitals" ThisKey="Patient_Id" OtherKey="Patient_Id" Type="Vital" />
      <Association Name="BloodType_Patient" Member="BloodType" ThisKey="BloodType_Id" OtherKey="BloodType_Id" Type="BloodType" IsForeignKey="true" />
      <Association Name="PatientStatus_Patient" Member="PatientStatus" ThisKey="PatientStatus_Id" OtherKey="PatientStatus_Id" Type="PatientStatus" IsForeignKey="true" />
      <Association Name="Staff_Patient" Member="Staff" ThisKey="Staff_Id" OtherKey="Staff_Id" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PatientStatus" Member="PatientStatus">
    <Type Name="PatientStatus">
      <Column Name="PatientStatus_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PatientStatus_Desc" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="PatientStatus_Patient" Member="Patients" ThisKey="PatientStatus_Id" OtherKey="PatientStatus_Id" Type="Patient" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="Staff_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Staff_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffRole_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StaffStatus_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Staff_Patient" Member="Patients" ThisKey="Staff_Id" OtherKey="Staff_Id" Type="Patient" />
      <Association Name="StaffRole_Staff" Member="StaffRole" ThisKey="StaffRole_Id" OtherKey="StaffRole_Id" Type="StaffRole" IsForeignKey="true" />
      <Association Name="StaffStatus_Staff" Member="StaffStatus" ThisKey="StaffStatus_Id" OtherKey="StaffStatus_Id" Type="StaffStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StaffRole" Member="StaffRoles">
    <Type Name="StaffRole">
      <Column Name="StaffRole_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffRole_Desc" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="StaffRole_Staff" Member="Staffs" ThisKey="StaffRole_Id" OtherKey="StaffRole_Id" Type="Staff" />
    </Type>
  </Table>
  <Table Name="dbo.StaffStatus" Member="StaffStatus">
    <Type Name="StaffStatus">
      <Column Name="StaffStatus_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffStatus_Desc" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="StaffStatus_Staff" Member="Staffs" ThisKey="StaffStatus_Id" OtherKey="StaffStatus_Id" Type="Staff" />
    </Type>
  </Table>
  <Table Name="dbo.Vitals" Member="Vitals">
    <Type Name="Vital">
      <Column Name="Vitals_Id" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Patient_Id" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Checkup_Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Patient_Temp" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Patient_PulseRate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Patient_Respiration" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Patient_Systolic" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Patient_Diastolic" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Staff_Id" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Patient_Vital" Member="Patient" ThisKey="Patient_Id" OtherKey="Patient_Id" Type="Patient" IsForeignKey="true" />
    </Type>
  </Table>
</Database>