#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2Y_2324_FinalsProject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PRMS")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBloodType(BloodType instance);
    partial void UpdateBloodType(BloodType instance);
    partial void DeleteBloodType(BloodType instance);
    partial void InsertCheckup(Checkup instance);
    partial void UpdateCheckup(Checkup instance);
    partial void DeleteCheckup(Checkup instance);
    partial void InsertDiagnosisStatus(DiagnosisStatus instance);
    partial void UpdateDiagnosisStatus(DiagnosisStatus instance);
    partial void DeleteDiagnosisStatus(DiagnosisStatus instance);
    partial void InsertHealthInfo(HealthInfo instance);
    partial void UpdateHealthInfo(HealthInfo instance);
    partial void DeleteHealthInfo(HealthInfo instance);
    partial void InsertPatient(Patient instance);
    partial void UpdatePatient(Patient instance);
    partial void DeletePatient(Patient instance);
    partial void InsertStaff(Staff instance);
    partial void UpdateStaff(Staff instance);
    partial void DeleteStaff(Staff instance);
    partial void InsertStaffRole(StaffRole instance);
    partial void UpdateStaffRole(StaffRole instance);
    partial void DeleteStaffRole(StaffRole instance);
    partial void InsertStaffStatus(StaffStatus instance);
    partial void UpdateStaffStatus(StaffStatus instance);
    partial void DeleteStaffStatus(StaffStatus instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::_2Y_2324_FinalsProject.Properties.Settings.Default.PRMSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BloodType> BloodTypes
		{
			get
			{
				return this.GetTable<BloodType>();
			}
		}
		
		public System.Data.Linq.Table<Checkup> Checkups
		{
			get
			{
				return this.GetTable<Checkup>();
			}
		}
		
		public System.Data.Linq.Table<DiagnosisStatus> DiagnosisStatus
		{
			get
			{
				return this.GetTable<DiagnosisStatus>();
			}
		}
		
		public System.Data.Linq.Table<HealthInfo> HealthInfos
		{
			get
			{
				return this.GetTable<HealthInfo>();
			}
		}
		
		public System.Data.Linq.Table<Patient> Patients
		{
			get
			{
				return this.GetTable<Patient>();
			}
		}
		
		public System.Data.Linq.Table<Staff> Staffs
		{
			get
			{
				return this.GetTable<Staff>();
			}
		}
		
		public System.Data.Linq.Table<StaffRole> StaffRoles
		{
			get
			{
				return this.GetTable<StaffRole>();
			}
		}
		
		public System.Data.Linq.Table<StaffStatus> StaffStatus
		{
			get
			{
				return this.GetTable<StaffStatus>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BloodType")]
	public partial class BloodType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BloodType_ID;
		
		private string _BloodType_Desc;
		
		private EntitySet<Patient> _Patients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBloodType_IDChanging(string value);
    partial void OnBloodType_IDChanged();
    partial void OnBloodType_DescChanging(string value);
    partial void OnBloodType_DescChanged();
    #endregion
		
		public BloodType()
		{
			this._Patients = new EntitySet<Patient>(new Action<Patient>(this.attach_Patients), new Action<Patient>(this.detach_Patients));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodType_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BloodType_ID
		{
			get
			{
				return this._BloodType_ID;
			}
			set
			{
				if ((this._BloodType_ID != value))
				{
					this.OnBloodType_IDChanging(value);
					this.SendPropertyChanging();
					this._BloodType_ID = value;
					this.SendPropertyChanged("BloodType_ID");
					this.OnBloodType_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodType_Desc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BloodType_Desc
		{
			get
			{
				return this._BloodType_Desc;
			}
			set
			{
				if ((this._BloodType_Desc != value))
				{
					this.OnBloodType_DescChanging(value);
					this.SendPropertyChanging();
					this._BloodType_Desc = value;
					this.SendPropertyChanged("BloodType_Desc");
					this.OnBloodType_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BloodType_Patient", Storage="_Patients", ThisKey="BloodType_ID", OtherKey="BloodType_ID")]
		public EntitySet<Patient> Patients
		{
			get
			{
				return this._Patients;
			}
			set
			{
				this._Patients.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Patients(Patient entity)
		{
			this.SendPropertyChanging();
			entity.BloodType = this;
		}
		
		private void detach_Patients(Patient entity)
		{
			this.SendPropertyChanging();
			entity.BloodType = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Checkup")]
	public partial class Checkup : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Checkup_ID;
		
		private string _Patient_ID;
		
		private System.DateTime _Checkup_Date;
		
		private int _Patient_Temp;
		
		private int _Patient_BP;
		
		private string _Staff_ID;
		
		private EntityRef<Patient> _Patient;
		
		private EntityRef<Staff> _Staff;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCheckup_IDChanging(string value);
    partial void OnCheckup_IDChanged();
    partial void OnPatient_IDChanging(string value);
    partial void OnPatient_IDChanged();
    partial void OnCheckup_DateChanging(System.DateTime value);
    partial void OnCheckup_DateChanged();
    partial void OnPatient_TempChanging(int value);
    partial void OnPatient_TempChanged();
    partial void OnPatient_BPChanging(int value);
    partial void OnPatient_BPChanged();
    partial void OnStaff_IDChanging(string value);
    partial void OnStaff_IDChanged();
    #endregion
		
		public Checkup()
		{
			this._Patient = default(EntityRef<Patient>);
			this._Staff = default(EntityRef<Staff>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checkup_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Checkup_ID
		{
			get
			{
				return this._Checkup_ID;
			}
			set
			{
				if ((this._Checkup_ID != value))
				{
					this.OnCheckup_IDChanging(value);
					this.SendPropertyChanging();
					this._Checkup_ID = value;
					this.SendPropertyChanged("Checkup_ID");
					this.OnCheckup_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_ID
		{
			get
			{
				return this._Patient_ID;
			}
			set
			{
				if ((this._Patient_ID != value))
				{
					if (this._Patient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPatient_IDChanging(value);
					this.SendPropertyChanging();
					this._Patient_ID = value;
					this.SendPropertyChanged("Patient_ID");
					this.OnPatient_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Checkup_Date", DbType="Date NOT NULL")]
		public System.DateTime Checkup_Date
		{
			get
			{
				return this._Checkup_Date;
			}
			set
			{
				if ((this._Checkup_Date != value))
				{
					this.OnCheckup_DateChanging(value);
					this.SendPropertyChanging();
					this._Checkup_Date = value;
					this.SendPropertyChanged("Checkup_Date");
					this.OnCheckup_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Temp", DbType="Int NOT NULL")]
		public int Patient_Temp
		{
			get
			{
				return this._Patient_Temp;
			}
			set
			{
				if ((this._Patient_Temp != value))
				{
					this.OnPatient_TempChanging(value);
					this.SendPropertyChanging();
					this._Patient_Temp = value;
					this.SendPropertyChanged("Patient_Temp");
					this.OnPatient_TempChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_BP", DbType="Int NOT NULL")]
		public int Patient_BP
		{
			get
			{
				return this._Patient_BP;
			}
			set
			{
				if ((this._Patient_BP != value))
				{
					this.OnPatient_BPChanging(value);
					this.SendPropertyChanging();
					this._Patient_BP = value;
					this.SendPropertyChanged("Patient_BP");
					this.OnPatient_BPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Staff_ID
		{
			get
			{
				return this._Staff_ID;
			}
			set
			{
				if ((this._Staff_ID != value))
				{
					if (this._Staff.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStaff_IDChanging(value);
					this.SendPropertyChanging();
					this._Staff_ID = value;
					this.SendPropertyChanged("Staff_ID");
					this.OnStaff_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Patient_Checkup", Storage="_Patient", ThisKey="Patient_ID", OtherKey="Patient_ID", IsForeignKey=true)]
		public Patient Patient
		{
			get
			{
				return this._Patient.Entity;
			}
			set
			{
				Patient previousValue = this._Patient.Entity;
				if (((previousValue != value) 
							|| (this._Patient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Patient.Entity = null;
						previousValue.Checkups.Remove(this);
					}
					this._Patient.Entity = value;
					if ((value != null))
					{
						value.Checkups.Add(this);
						this._Patient_ID = value.Patient_ID;
					}
					else
					{
						this._Patient_ID = default(string);
					}
					this.SendPropertyChanged("Patient");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Staff_Checkup", Storage="_Staff", ThisKey="Staff_ID", OtherKey="Staff_ID", IsForeignKey=true)]
		public Staff Staff
		{
			get
			{
				return this._Staff.Entity;
			}
			set
			{
				Staff previousValue = this._Staff.Entity;
				if (((previousValue != value) 
							|| (this._Staff.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Staff.Entity = null;
						previousValue.Checkups.Remove(this);
					}
					this._Staff.Entity = value;
					if ((value != null))
					{
						value.Checkups.Add(this);
						this._Staff_ID = value.Staff_ID;
					}
					else
					{
						this._Staff_ID = default(string);
					}
					this.SendPropertyChanged("Staff");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiagnosisStatus")]
	public partial class DiagnosisStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DiagnosisStatus_ID;
		
		private string _DiagnosisStatus_Desc;
		
		private EntitySet<Patient> _Patients;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDiagnosisStatus_IDChanging(string value);
    partial void OnDiagnosisStatus_IDChanged();
    partial void OnDiagnosisStatus_DescChanging(string value);
    partial void OnDiagnosisStatus_DescChanged();
    #endregion
		
		public DiagnosisStatus()
		{
			this._Patients = new EntitySet<Patient>(new Action<Patient>(this.attach_Patients), new Action<Patient>(this.detach_Patients));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiagnosisStatus_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string DiagnosisStatus_ID
		{
			get
			{
				return this._DiagnosisStatus_ID;
			}
			set
			{
				if ((this._DiagnosisStatus_ID != value))
				{
					this.OnDiagnosisStatus_IDChanging(value);
					this.SendPropertyChanging();
					this._DiagnosisStatus_ID = value;
					this.SendPropertyChanged("DiagnosisStatus_ID");
					this.OnDiagnosisStatus_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiagnosisStatus_Desc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DiagnosisStatus_Desc
		{
			get
			{
				return this._DiagnosisStatus_Desc;
			}
			set
			{
				if ((this._DiagnosisStatus_Desc != value))
				{
					this.OnDiagnosisStatus_DescChanging(value);
					this.SendPropertyChanging();
					this._DiagnosisStatus_Desc = value;
					this.SendPropertyChanged("DiagnosisStatus_Desc");
					this.OnDiagnosisStatus_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiagnosisStatus_Patient", Storage="_Patients", ThisKey="DiagnosisStatus_ID", OtherKey="DiagnosisStatus_ID")]
		public EntitySet<Patient> Patients
		{
			get
			{
				return this._Patients;
			}
			set
			{
				this._Patients.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Patients(Patient entity)
		{
			this.SendPropertyChanging();
			entity.DiagnosisStatus = this;
		}
		
		private void detach_Patients(Patient entity)
		{
			this.SendPropertyChanging();
			entity.DiagnosisStatus = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HealthInfo")]
	public partial class HealthInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _HealthInfo_ID;
		
		private string _Patient_ID;
		
		private string _HealthInfo_Medications;
		
		private string _HealthInfo_Allergies;
		
		private string _HealthInfo_Surgeries;
		
		private string _HealthInfo_FamilyHistory;
		
		private EntityRef<Patient> _Patient;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHealthInfo_IDChanging(string value);
    partial void OnHealthInfo_IDChanged();
    partial void OnPatient_IDChanging(string value);
    partial void OnPatient_IDChanged();
    partial void OnHealthInfo_MedicationsChanging(string value);
    partial void OnHealthInfo_MedicationsChanged();
    partial void OnHealthInfo_AllergiesChanging(string value);
    partial void OnHealthInfo_AllergiesChanged();
    partial void OnHealthInfo_SurgeriesChanging(string value);
    partial void OnHealthInfo_SurgeriesChanged();
    partial void OnHealthInfo_FamilyHistoryChanging(string value);
    partial void OnHealthInfo_FamilyHistoryChanged();
    #endregion
		
		public HealthInfo()
		{
			this._Patient = default(EntityRef<Patient>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthInfo_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string HealthInfo_ID
		{
			get
			{
				return this._HealthInfo_ID;
			}
			set
			{
				if ((this._HealthInfo_ID != value))
				{
					this.OnHealthInfo_IDChanging(value);
					this.SendPropertyChanging();
					this._HealthInfo_ID = value;
					this.SendPropertyChanged("HealthInfo_ID");
					this.OnHealthInfo_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_ID
		{
			get
			{
				return this._Patient_ID;
			}
			set
			{
				if ((this._Patient_ID != value))
				{
					if (this._Patient.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPatient_IDChanging(value);
					this.SendPropertyChanging();
					this._Patient_ID = value;
					this.SendPropertyChanged("Patient_ID");
					this.OnPatient_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthInfo_Medications", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HealthInfo_Medications
		{
			get
			{
				return this._HealthInfo_Medications;
			}
			set
			{
				if ((this._HealthInfo_Medications != value))
				{
					this.OnHealthInfo_MedicationsChanging(value);
					this.SendPropertyChanging();
					this._HealthInfo_Medications = value;
					this.SendPropertyChanged("HealthInfo_Medications");
					this.OnHealthInfo_MedicationsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthInfo_Allergies", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HealthInfo_Allergies
		{
			get
			{
				return this._HealthInfo_Allergies;
			}
			set
			{
				if ((this._HealthInfo_Allergies != value))
				{
					this.OnHealthInfo_AllergiesChanging(value);
					this.SendPropertyChanging();
					this._HealthInfo_Allergies = value;
					this.SendPropertyChanged("HealthInfo_Allergies");
					this.OnHealthInfo_AllergiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthInfo_Surgeries", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HealthInfo_Surgeries
		{
			get
			{
				return this._HealthInfo_Surgeries;
			}
			set
			{
				if ((this._HealthInfo_Surgeries != value))
				{
					this.OnHealthInfo_SurgeriesChanging(value);
					this.SendPropertyChanging();
					this._HealthInfo_Surgeries = value;
					this.SendPropertyChanged("HealthInfo_Surgeries");
					this.OnHealthInfo_SurgeriesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HealthInfo_FamilyHistory", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string HealthInfo_FamilyHistory
		{
			get
			{
				return this._HealthInfo_FamilyHistory;
			}
			set
			{
				if ((this._HealthInfo_FamilyHistory != value))
				{
					this.OnHealthInfo_FamilyHistoryChanging(value);
					this.SendPropertyChanging();
					this._HealthInfo_FamilyHistory = value;
					this.SendPropertyChanged("HealthInfo_FamilyHistory");
					this.OnHealthInfo_FamilyHistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Patient_HealthInfo", Storage="_Patient", ThisKey="Patient_ID", OtherKey="Patient_ID", IsForeignKey=true)]
		public Patient Patient
		{
			get
			{
				return this._Patient.Entity;
			}
			set
			{
				Patient previousValue = this._Patient.Entity;
				if (((previousValue != value) 
							|| (this._Patient.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Patient.Entity = null;
						previousValue.HealthInfos.Remove(this);
					}
					this._Patient.Entity = value;
					if ((value != null))
					{
						value.HealthInfos.Add(this);
						this._Patient_ID = value.Patient_ID;
					}
					else
					{
						this._Patient_ID = default(string);
					}
					this.SendPropertyChanged("Patient");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Patient")]
	public partial class Patient : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Patient_Image;
		
		private string _Patient_ID;
		
		private string _Patient_Name;
		
		private string _Patient_Sex;
		
		private int _Patient_Age;
		
		private System.DateTime _Patient_Birth;
		
		private string _BloodType_ID;
		
		private string _Patient_EmergencyContactName;
		
		private string _Patient_EmergencyContactNum;
		
		private string _DiagnosisStatus_ID;
		
		private EntitySet<Checkup> _Checkups;
		
		private EntitySet<HealthInfo> _HealthInfos;
		
		private EntityRef<BloodType> _BloodType;
		
		private EntityRef<DiagnosisStatus> _DiagnosisStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPatient_ImageChanging(string value);
    partial void OnPatient_ImageChanged();
    partial void OnPatient_IDChanging(string value);
    partial void OnPatient_IDChanged();
    partial void OnPatient_NameChanging(string value);
    partial void OnPatient_NameChanged();
    partial void OnPatient_SexChanging(string value);
    partial void OnPatient_SexChanged();
    partial void OnPatient_AgeChanging(int value);
    partial void OnPatient_AgeChanged();
    partial void OnPatient_BirthChanging(System.DateTime value);
    partial void OnPatient_BirthChanged();
    partial void OnBloodType_IDChanging(string value);
    partial void OnBloodType_IDChanged();
    partial void OnPatient_EmergencyContactNameChanging(string value);
    partial void OnPatient_EmergencyContactNameChanged();
    partial void OnPatient_EmergencyContactNumChanging(string value);
    partial void OnPatient_EmergencyContactNumChanged();
    partial void OnDiagnosisStatus_IDChanging(string value);
    partial void OnDiagnosisStatus_IDChanged();
    #endregion
		
		public Patient()
		{
			this._Checkups = new EntitySet<Checkup>(new Action<Checkup>(this.attach_Checkups), new Action<Checkup>(this.detach_Checkups));
			this._HealthInfos = new EntitySet<HealthInfo>(new Action<HealthInfo>(this.attach_HealthInfos), new Action<HealthInfo>(this.detach_HealthInfos));
			this._BloodType = default(EntityRef<BloodType>);
			this._DiagnosisStatus = default(EntityRef<DiagnosisStatus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Image", DbType="VarChar(100)")]
		public string Patient_Image
		{
			get
			{
				return this._Patient_Image;
			}
			set
			{
				if ((this._Patient_Image != value))
				{
					this.OnPatient_ImageChanging(value);
					this.SendPropertyChanging();
					this._Patient_Image = value;
					this.SendPropertyChanged("Patient_Image");
					this.OnPatient_ImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Patient_ID
		{
			get
			{
				return this._Patient_ID;
			}
			set
			{
				if ((this._Patient_ID != value))
				{
					this.OnPatient_IDChanging(value);
					this.SendPropertyChanging();
					this._Patient_ID = value;
					this.SendPropertyChanged("Patient_ID");
					this.OnPatient_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_Name
		{
			get
			{
				return this._Patient_Name;
			}
			set
			{
				if ((this._Patient_Name != value))
				{
					this.OnPatient_NameChanging(value);
					this.SendPropertyChanging();
					this._Patient_Name = value;
					this.SendPropertyChanged("Patient_Name");
					this.OnPatient_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Sex", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_Sex
		{
			get
			{
				return this._Patient_Sex;
			}
			set
			{
				if ((this._Patient_Sex != value))
				{
					this.OnPatient_SexChanging(value);
					this.SendPropertyChanging();
					this._Patient_Sex = value;
					this.SendPropertyChanged("Patient_Sex");
					this.OnPatient_SexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Age", DbType="Int NOT NULL")]
		public int Patient_Age
		{
			get
			{
				return this._Patient_Age;
			}
			set
			{
				if ((this._Patient_Age != value))
				{
					this.OnPatient_AgeChanging(value);
					this.SendPropertyChanging();
					this._Patient_Age = value;
					this.SendPropertyChanged("Patient_Age");
					this.OnPatient_AgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_Birth", DbType="Date NOT NULL")]
		public System.DateTime Patient_Birth
		{
			get
			{
				return this._Patient_Birth;
			}
			set
			{
				if ((this._Patient_Birth != value))
				{
					this.OnPatient_BirthChanging(value);
					this.SendPropertyChanging();
					this._Patient_Birth = value;
					this.SendPropertyChanged("Patient_Birth");
					this.OnPatient_BirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodType_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BloodType_ID
		{
			get
			{
				return this._BloodType_ID;
			}
			set
			{
				if ((this._BloodType_ID != value))
				{
					if (this._BloodType.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBloodType_IDChanging(value);
					this.SendPropertyChanging();
					this._BloodType_ID = value;
					this.SendPropertyChanged("BloodType_ID");
					this.OnBloodType_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_EmergencyContactName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_EmergencyContactName
		{
			get
			{
				return this._Patient_EmergencyContactName;
			}
			set
			{
				if ((this._Patient_EmergencyContactName != value))
				{
					this.OnPatient_EmergencyContactNameChanging(value);
					this.SendPropertyChanging();
					this._Patient_EmergencyContactName = value;
					this.SendPropertyChanged("Patient_EmergencyContactName");
					this.OnPatient_EmergencyContactNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Patient_EmergencyContactNum", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Patient_EmergencyContactNum
		{
			get
			{
				return this._Patient_EmergencyContactNum;
			}
			set
			{
				if ((this._Patient_EmergencyContactNum != value))
				{
					this.OnPatient_EmergencyContactNumChanging(value);
					this.SendPropertyChanging();
					this._Patient_EmergencyContactNum = value;
					this.SendPropertyChanged("Patient_EmergencyContactNum");
					this.OnPatient_EmergencyContactNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiagnosisStatus_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DiagnosisStatus_ID
		{
			get
			{
				return this._DiagnosisStatus_ID;
			}
			set
			{
				if ((this._DiagnosisStatus_ID != value))
				{
					if (this._DiagnosisStatus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDiagnosisStatus_IDChanging(value);
					this.SendPropertyChanging();
					this._DiagnosisStatus_ID = value;
					this.SendPropertyChanged("DiagnosisStatus_ID");
					this.OnDiagnosisStatus_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Patient_Checkup", Storage="_Checkups", ThisKey="Patient_ID", OtherKey="Patient_ID")]
		public EntitySet<Checkup> Checkups
		{
			get
			{
				return this._Checkups;
			}
			set
			{
				this._Checkups.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Patient_HealthInfo", Storage="_HealthInfos", ThisKey="Patient_ID", OtherKey="Patient_ID")]
		public EntitySet<HealthInfo> HealthInfos
		{
			get
			{
				return this._HealthInfos;
			}
			set
			{
				this._HealthInfos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BloodType_Patient", Storage="_BloodType", ThisKey="BloodType_ID", OtherKey="BloodType_ID", IsForeignKey=true)]
		public BloodType BloodType
		{
			get
			{
				return this._BloodType.Entity;
			}
			set
			{
				BloodType previousValue = this._BloodType.Entity;
				if (((previousValue != value) 
							|| (this._BloodType.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BloodType.Entity = null;
						previousValue.Patients.Remove(this);
					}
					this._BloodType.Entity = value;
					if ((value != null))
					{
						value.Patients.Add(this);
						this._BloodType_ID = value.BloodType_ID;
					}
					else
					{
						this._BloodType_ID = default(string);
					}
					this.SendPropertyChanged("BloodType");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiagnosisStatus_Patient", Storage="_DiagnosisStatus", ThisKey="DiagnosisStatus_ID", OtherKey="DiagnosisStatus_ID", IsForeignKey=true)]
		public DiagnosisStatus DiagnosisStatus
		{
			get
			{
				return this._DiagnosisStatus.Entity;
			}
			set
			{
				DiagnosisStatus previousValue = this._DiagnosisStatus.Entity;
				if (((previousValue != value) 
							|| (this._DiagnosisStatus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiagnosisStatus.Entity = null;
						previousValue.Patients.Remove(this);
					}
					this._DiagnosisStatus.Entity = value;
					if ((value != null))
					{
						value.Patients.Add(this);
						this._DiagnosisStatus_ID = value.DiagnosisStatus_ID;
					}
					else
					{
						this._DiagnosisStatus_ID = default(string);
					}
					this.SendPropertyChanged("DiagnosisStatus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Checkups(Checkup entity)
		{
			this.SendPropertyChanging();
			entity.Patient = this;
		}
		
		private void detach_Checkups(Checkup entity)
		{
			this.SendPropertyChanging();
			entity.Patient = null;
		}
		
		private void attach_HealthInfos(HealthInfo entity)
		{
			this.SendPropertyChanging();
			entity.Patient = this;
		}
		
		private void detach_HealthInfos(HealthInfo entity)
		{
			this.SendPropertyChanging();
			entity.Patient = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Staff")]
	public partial class Staff : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Staff_ID;
		
		private string _Staff_Name;
		
		private string _Staff_Password;
		
		private string _StaffRole_ID;
		
		private string _StaffStatus_ID;
		
		private EntitySet<Checkup> _Checkups;
		
		private EntityRef<StaffRole> _StaffRole;
		
		private EntityRef<StaffStatus> _StaffStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaff_IDChanging(string value);
    partial void OnStaff_IDChanged();
    partial void OnStaff_NameChanging(string value);
    partial void OnStaff_NameChanged();
    partial void OnStaff_PasswordChanging(string value);
    partial void OnStaff_PasswordChanged();
    partial void OnStaffRole_IDChanging(string value);
    partial void OnStaffRole_IDChanged();
    partial void OnStaffStatus_IDChanging(string value);
    partial void OnStaffStatus_IDChanged();
    #endregion
		
		public Staff()
		{
			this._Checkups = new EntitySet<Checkup>(new Action<Checkup>(this.attach_Checkups), new Action<Checkup>(this.detach_Checkups));
			this._StaffRole = default(EntityRef<StaffRole>);
			this._StaffStatus = default(EntityRef<StaffStatus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Staff_ID
		{
			get
			{
				return this._Staff_ID;
			}
			set
			{
				if ((this._Staff_ID != value))
				{
					this.OnStaff_IDChanging(value);
					this.SendPropertyChanging();
					this._Staff_ID = value;
					this.SendPropertyChanged("Staff_ID");
					this.OnStaff_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Staff_Name
		{
			get
			{
				return this._Staff_Name;
			}
			set
			{
				if ((this._Staff_Name != value))
				{
					this.OnStaff_NameChanging(value);
					this.SendPropertyChanging();
					this._Staff_Name = value;
					this.SendPropertyChanged("Staff_Name");
					this.OnStaff_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Staff_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Staff_Password
		{
			get
			{
				return this._Staff_Password;
			}
			set
			{
				if ((this._Staff_Password != value))
				{
					this.OnStaff_PasswordChanging(value);
					this.SendPropertyChanging();
					this._Staff_Password = value;
					this.SendPropertyChanged("Staff_Password");
					this.OnStaff_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffRole_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StaffRole_ID
		{
			get
			{
				return this._StaffRole_ID;
			}
			set
			{
				if ((this._StaffRole_ID != value))
				{
					if (this._StaffRole.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStaffRole_IDChanging(value);
					this.SendPropertyChanging();
					this._StaffRole_ID = value;
					this.SendPropertyChanged("StaffRole_ID");
					this.OnStaffRole_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffStatus_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StaffStatus_ID
		{
			get
			{
				return this._StaffStatus_ID;
			}
			set
			{
				if ((this._StaffStatus_ID != value))
				{
					if (this._StaffStatus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStaffStatus_IDChanging(value);
					this.SendPropertyChanging();
					this._StaffStatus_ID = value;
					this.SendPropertyChanged("StaffStatus_ID");
					this.OnStaffStatus_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Staff_Checkup", Storage="_Checkups", ThisKey="Staff_ID", OtherKey="Staff_ID")]
		public EntitySet<Checkup> Checkups
		{
			get
			{
				return this._Checkups;
			}
			set
			{
				this._Checkups.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StaffRole_Staff", Storage="_StaffRole", ThisKey="StaffRole_ID", OtherKey="StaffRole_ID", IsForeignKey=true)]
		public StaffRole StaffRole
		{
			get
			{
				return this._StaffRole.Entity;
			}
			set
			{
				StaffRole previousValue = this._StaffRole.Entity;
				if (((previousValue != value) 
							|| (this._StaffRole.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StaffRole.Entity = null;
						previousValue.Staffs.Remove(this);
					}
					this._StaffRole.Entity = value;
					if ((value != null))
					{
						value.Staffs.Add(this);
						this._StaffRole_ID = value.StaffRole_ID;
					}
					else
					{
						this._StaffRole_ID = default(string);
					}
					this.SendPropertyChanged("StaffRole");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StaffStatus_Staff", Storage="_StaffStatus", ThisKey="StaffStatus_ID", OtherKey="StaffStatus_ID", IsForeignKey=true)]
		public StaffStatus StaffStatus
		{
			get
			{
				return this._StaffStatus.Entity;
			}
			set
			{
				StaffStatus previousValue = this._StaffStatus.Entity;
				if (((previousValue != value) 
							|| (this._StaffStatus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._StaffStatus.Entity = null;
						previousValue.Staffs.Remove(this);
					}
					this._StaffStatus.Entity = value;
					if ((value != null))
					{
						value.Staffs.Add(this);
						this._StaffStatus_ID = value.StaffStatus_ID;
					}
					else
					{
						this._StaffStatus_ID = default(string);
					}
					this.SendPropertyChanged("StaffStatus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Checkups(Checkup entity)
		{
			this.SendPropertyChanging();
			entity.Staff = this;
		}
		
		private void detach_Checkups(Checkup entity)
		{
			this.SendPropertyChanging();
			entity.Staff = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StaffRole")]
	public partial class StaffRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StaffRole_ID;
		
		private string _StaffRole_Desc;
		
		private EntitySet<Staff> _Staffs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaffRole_IDChanging(string value);
    partial void OnStaffRole_IDChanged();
    partial void OnStaffRole_DescChanging(string value);
    partial void OnStaffRole_DescChanged();
    #endregion
		
		public StaffRole()
		{
			this._Staffs = new EntitySet<Staff>(new Action<Staff>(this.attach_Staffs), new Action<Staff>(this.detach_Staffs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffRole_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StaffRole_ID
		{
			get
			{
				return this._StaffRole_ID;
			}
			set
			{
				if ((this._StaffRole_ID != value))
				{
					this.OnStaffRole_IDChanging(value);
					this.SendPropertyChanging();
					this._StaffRole_ID = value;
					this.SendPropertyChanged("StaffRole_ID");
					this.OnStaffRole_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffRole_Desc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StaffRole_Desc
		{
			get
			{
				return this._StaffRole_Desc;
			}
			set
			{
				if ((this._StaffRole_Desc != value))
				{
					this.OnStaffRole_DescChanging(value);
					this.SendPropertyChanging();
					this._StaffRole_Desc = value;
					this.SendPropertyChanged("StaffRole_Desc");
					this.OnStaffRole_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StaffRole_Staff", Storage="_Staffs", ThisKey="StaffRole_ID", OtherKey="StaffRole_ID")]
		public EntitySet<Staff> Staffs
		{
			get
			{
				return this._Staffs;
			}
			set
			{
				this._Staffs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Staffs(Staff entity)
		{
			this.SendPropertyChanging();
			entity.StaffRole = this;
		}
		
		private void detach_Staffs(Staff entity)
		{
			this.SendPropertyChanging();
			entity.StaffRole = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StaffStatus")]
	public partial class StaffStatus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _StaffStatus_ID;
		
		private string _StaffStatus_Desc;
		
		private EntitySet<Staff> _Staffs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStaffStatus_IDChanging(string value);
    partial void OnStaffStatus_IDChanged();
    partial void OnStaffStatus_DescChanging(string value);
    partial void OnStaffStatus_DescChanged();
    #endregion
		
		public StaffStatus()
		{
			this._Staffs = new EntitySet<Staff>(new Action<Staff>(this.attach_Staffs), new Action<Staff>(this.detach_Staffs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffStatus_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StaffStatus_ID
		{
			get
			{
				return this._StaffStatus_ID;
			}
			set
			{
				if ((this._StaffStatus_ID != value))
				{
					this.OnStaffStatus_IDChanging(value);
					this.SendPropertyChanging();
					this._StaffStatus_ID = value;
					this.SendPropertyChanged("StaffStatus_ID");
					this.OnStaffStatus_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StaffStatus_Desc", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string StaffStatus_Desc
		{
			get
			{
				return this._StaffStatus_Desc;
			}
			set
			{
				if ((this._StaffStatus_Desc != value))
				{
					this.OnStaffStatus_DescChanging(value);
					this.SendPropertyChanging();
					this._StaffStatus_Desc = value;
					this.SendPropertyChanged("StaffStatus_Desc");
					this.OnStaffStatus_DescChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="StaffStatus_Staff", Storage="_Staffs", ThisKey="StaffStatus_ID", OtherKey="StaffStatus_ID")]
		public EntitySet<Staff> Staffs
		{
			get
			{
				return this._Staffs;
			}
			set
			{
				this._Staffs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Staffs(Staff entity)
		{
			this.SendPropertyChanging();
			entity.StaffStatus = this;
		}
		
		private void detach_Staffs(Staff entity)
		{
			this.SendPropertyChanging();
			entity.StaffStatus = null;
		}
	}
}
#pragma warning restore 1591
